#!/bin/sh

grep -v cited |
awk -F, '{print $3, $2; print $7, $6}' |
sort | uniq |
awk '{
	print $1, $2;
	if ($2 < 0) {
		print $1, $2 + 360;
	} else {
		print $1, $2 - 360;
	}
}' |
./voronoi/voronoi -t |
awk '{
	print $2, $4;
	print $2, $6;
	print $4, $6;
}' |
tr ',' ' ' |
awk '{
	if (($2 < -180 || $2 > 180) && ($4 < -180 || $4 > 180)) {
		#print "SKIP " $1 "," $2 " " $3 "," $4;
		# both off the earth, so duplicate
	} else {
		if ($2 < -180) {
			$2 += 360;
		}
		if ($2 > 180) {
			$2 -= 360;
		}
		if ($4 < -180) {
			$4 += 360;
		}
		if ($4 > 180) {
			$4 -= 360;
		}

		print $1 "," $2 " " $3 "," $4;
	}
}'
